### ISSUE TITLE
Pull data from winstonslab

### ISSUE THREAD

**Issue by RyanYip** [CyberKronos/teamcomp#64]
-Pull player/match data from winstonslab (ie. https://www.winstonslab.com/matches/match.php?id=2584)
-Be able to cycle through all players/matches (depending on how the structure of the site is setup, either per player data or per match data)
-Structure data in script for easy re-use (ie. python dict so we can output into SQL queries)

**Comment by raymondhuynh** [comment]
If we're taking the route of "get more first, trim later", would this structure work? 
https://docs.google.com/spreadsheets/d/1DavxeKF_96gw7cTVaArQ_7mTIiZEsmOHEvTU36wyKWI/edit?usp=sharing

**Comment by CyberKronos** [comment]
is this still needed?

**Comment by RyanYip** [comment]
No, unless Raymond wants to act on the older stats which we missed. Script is nearly completed (I think) so I'll probably just finish it up at some point anyways and we can do what we want.

**Comment by RyanYip** [comment]
Closing this as I'm not actually going to finish it. No need for this data anymore :D
