### ISSUE TITLE
As a user, I am able to filter by a league of legends league in my collections

### ISSUE THREAD

**Issue by CyberKronos** [CyberKronos/teamcomp#78]
As a user, 
I am able to filter by a league in my collections,
So that I can find player cards in the relevant eSports league

#### Satisfaction Criteria
1. I am able to see league filters for LoL and Overwatch
**LoL** = LCS and LEC
**Overwatch** = OWL
2. I am able to successfully toggle between the multiple leagues when available. Else, should default to the one league
3. I am able to successfully see my collection filtered properly

#### Technical Notes
1. Ensure that filters are properly propagated through Redux and stored.
2. The player card component isn't finished yet, so the easiest way to test this is to see it is stored in redux.

**Comment by lukezhang454** [comment]
Merged in #79
